version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stellar_spark_backend
    ports:
      - "8000:8000"
    volumes:
      - ./jodi.db:/app/jodi.db
      - ./firebase-credentials.json:/app/firebase-credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    restart: unless-stopped
